game_options:
  - dictator_sender
  - dictator_receiver
  - dictator_sequential
  - ultimatum_sender
  - ultimatum_receiver
mode_options:
  - test_assumptions
  - prepare_prompts
  - send_prompts_baseline
  - send_prompts_experimental
model_options:
  - chatgpt
  - davinci