game_options:
  - dictator_sender
  - dictator_binary
  - dictator_sequential
  - ultimatum_sender
  - ultimatum_receiver
mode_options:
  - test_assumptions
  - prepare_prompts
  - send_prompts_baseline
  - send_prompts_experimental
model_options:
  - gpt-35-turbo
  - text-davinci-003
n: 1000